### ISSUE TITLE
WEB : Issue list / Labels btn + Milestones btn

### ISSUE THREAD

**Issue by gitdog01** [boostcamp-2020/IssueTracker-3#122]
- [x]  label 개수

- [x]  label list로 이동

- [x] open milestone 개수

- [x] milestone list로 이동

**Comment by gitdog01** [comment]
컷 !!
